title: Intrusion Detection Tools
description: Reacquainting with SimSpace, demonstrating an ICMP stream, and analyzing tools for intrusion detection
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
